name: thesis-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=12.3.2
  - icu=78.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcups=2.3.3
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.1
  - packaging=26.0
  - pandas=3.0.0
  - pcre2=10.47
  - pillow=12.1.0
  - pip=26.0
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyparsing=3.3.2
  - pyside6=6.10.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - qhull=2020.2
  - qt6-main=6.10.2
  - readline=8.3
  - setuptools=80.10.2
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.5.4
  - tzdata=2025c
  - unicodedata2=17.0.0
  - wayland=1.24.0
  - wheel=0.46.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - click==8.3.1
      - dynamic-network-architectures==0.4.3
      - einops==0.8.2
      - filelock==3.20.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.0
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - monai==1.5.2
      - mpmath==1.3.0
      - networkx==3.6.1
      - nibabel==5.3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.13.0.92
      - psutil==7.2.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - safetensors==0.7.0
      - shellingham==1.5.4
      - sympy==1.13.1
      - timm==1.0.22
      - tokenizers==0.22.2
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - transformers==5.0.0
      - triton==3.1.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
